services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A musicplatform worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis


volumes:
  postgres_data: