# Generated by Django 5.2.1 on 2025-05-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_artist_track_duration_playlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set(),
        ),
    ]
